### ISSUE TITLE
Error on map - "This page can't load Google Maps correctly"

### ISSUE THREAD

**Issue by abhijitnandy** [DanielGallo/CustomersMapApp#1]
I got the app working with the connection between the grid and the map. Clicking on any grid row would navigate the map to the right location and clicking on any map marker would select the correct row on the grid.

However, the Google Map had a gray overlay with a message -
"This page can't load Google Maps correctly".

I have added the API Key in app.json in the "mashups".

I also get this error in the Dev Tools console, with a link -
"Google Maps JavaScript API warning: NoApiKeys"

The link shows this -
https://developers.google.com/maps/documentation/javascript/error-messages#no-api-keys

which effectively means that the API key entered didn't take.

I'm using ExtJs 7.2.0 commercial version.

**Comment by hirenkanetiya76** [comment]
i am not able to run the Google Maps correctly. even i have create a API key and enabled a Google Maps Javascript API on google console with all the required billing details.

But i have put that generated Key on my app.json
like 
"mashup": {
    "map": {
        "options": "?key=Hear_I_Have_put_my_API_Key"
    }
  },
  
  And also add a package dependency 
  
  "requires": [
    "google",
    "ux"
   ]
   
   But then also i am not able to render the google maps on my screen.
   
   
   I am getting this 403 forbidden error on console.
   GET http://maps.googleapis.com/maps/api/mapsjs/gen_204?csp_test=true 403 (Forbidden)
   i am getting this response on network tab.
   
   {
  "error": {
    "code": 403,
    "message": "SSL is required to perform this operation.",
    "status": "PERMISSION_DENIED"
  }
}

Can you pls tell me what i have missing steps for just load a simple google maps on scree.

I'm using ExtJs 7.1.0 commercial version.

**Comment by abhijitnandy** [comment]
We had to add the following `<script>` tag in `index.html`

`<script type="text/javascript" src="https://maps.googleapis.com/maps/api/js?v=3&key=your_key_here" async defer></script>`

besides the key in under `mashup` in `app.json`

`
"mashup": {
  "map": {
    "options": "?key=your_key_here"
  }
},
`
